export const dict = {
  ru: {
    app_name: 'Ritmo',
    tab_today: 'Сегодня', tab_habits: 'Привычки', tab_stats: 'Прогресс', tab_settings: 'Ещё',

    cat_body: 'Тело', cat_mind: 'Разум', cat_health: 'Здоровье', cat_work: 'Работа',
    when_morning: 'Утро', when_day: 'День', when_evening: 'Вечер', when_any: 'Когда угодно',

    day_progress: 'День пройден на', all_done: 'Все дела на сегодня закрыты',
    all_done_sub: 'Так держать. Завтра — новый круг.',
    nothing_today: 'На сегодня ничего не запланировано',
    nothing_today_sub: 'Добавьте привычку или включите её на этот день недели.',
    streak: 'Подряд', streak_days: 'дней подряд', best_streak: 'Лучшая серия',
    done_today: 'Сделано сегодня',

    add_habit: 'Новая привычка', edit_habit: 'Привычка',
    habit_title: 'Что делаем', habit_title_ph: 'Например: читать 20 страниц',
    habit_cat: 'Область жизни', habit_when: 'Когда',
    habit_type: 'Как считаем',
    type_check: 'Отметка «сделал»', type_count: 'Количество',
    habit_unit: 'Единица', habit_unit_ph: 'страниц, минут, стаканов',
    habit_target: 'Цель за день',
    habit_freq: 'Как часто', freq_daily: 'Каждый день',
    freq_days: 'По дням недели', freq_week: 'Сколько раз в неделю',
    per_week: 'Раз в неделю',
    habit_icon: 'Значок',
    habit_archive: 'Убрать из списка', habit_restore: 'Вернуть в список',
    archived: 'В архиве', archived_n: 'В архиве: {n}',

    no_habits: 'Привычек пока нет',
    no_habits_sub: 'Начните с двух-трёх — их проще удержать, чем десять сразу.',
    add_starter: 'Добавить готовый набор',
    starter_added: 'Набор привычек добавлен',

    note_today: 'Заметка дня', note_ph: 'Как прошёл день, что мешало, что получилось',
    mood: 'Самочувствие',
    mood_1: 'Тяжело', mood_2: 'Так себе', mood_3: 'Нормально', mood_4: 'Хорошо', mood_5: 'Отлично',

    stats_week: 'Эта неделя', stats_month: 'Этот месяц', stats_year: 'Год',
    completion: 'Выполнение', calendar: 'Календарь',
    by_habit: 'По привычкам', by_area: 'По областям жизни',
    days_active: 'Дней с отметками', total_done: 'Всего выполнено',
    perfect_days: 'Идеальных дней', perfect_days_hint: 'Дни, когда закрыто всё запланированное',
    no_stats: 'Данных пока мало',
    no_stats_sub: 'Отмечайте привычки несколько дней — здесь появятся графики и серии.',

    reminders: 'Напоминания', reminders_on: 'Напоминать о привычках',
    reminder_time: 'Во сколько', reminders_denied: 'Уведомления запрещены в настройках телефона',
    reminders_ios: 'На iPhone напоминания приходят, только если приложение добавлено на экран «Домой».',
    reminders_hint: 'Напоминание приходит, пока приложение открыто или свёрнуто. Для надёжности поставьте будильник.',

    week_start: 'Неделя начинается с', ws_mon: 'Понедельника', ws_sun: 'Воскресенья',
    backup: 'Резервная копия',
    backup_hint: 'Данные хранятся только на этом телефоне. Делайте копию раз в месяц.',

    of_n: 'из {n}',
    times_week: '{n}× в неделю',
    done_n_times: 'Выполнено {n} раз',
    tap_to_add: 'Нажмите, чтобы добавить',
    mon: 'Пн', tue: 'Вт', wed: 'Ср', thu: 'Чт', fri: 'Пт', sat: 'Сб', sun: 'Вс',
  },

  es: {
    app_name: 'Ritmo',
    tab_today: 'Hoy', tab_habits: 'Hábitos', tab_stats: 'Progreso', tab_settings: 'Más',
    cat_body: 'Cuerpo', cat_mind: 'Mente', cat_health: 'Salud', cat_work: 'Trabajo',
    when_morning: 'Mañana', when_day: 'Tarde', when_evening: 'Noche', when_any: 'Cuando sea',
    day_progress: 'Día completado al', all_done: 'Todo lo de hoy está hecho',
    all_done_sub: 'Sigue así. Mañana, otra vuelta.',
    nothing_today: 'Nada planeado para hoy',
    nothing_today_sub: 'Añade un hábito o actívalo para este día.',
    streak: 'Racha', streak_days: 'días seguidos', best_streak: 'Mejor racha',
    done_today: 'Hecho hoy',
    add_habit: 'Nuevo hábito', edit_habit: 'Hábito',
    habit_title: 'Qué hacemos', habit_title_ph: 'Ej.: leer 20 páginas',
    habit_cat: 'Área de vida', habit_when: 'Cuándo',
    habit_type: 'Cómo se mide',
    type_check: 'Marca de «hecho»', type_count: 'Cantidad',
    habit_unit: 'Unidad', habit_unit_ph: 'páginas, minutos, vasos',
    habit_target: 'Meta diaria',
    habit_freq: 'Frecuencia', freq_daily: 'Todos los días',
    freq_days: 'Días de la semana', freq_week: 'Veces por semana',
    per_week: 'Veces por semana',
    habit_icon: 'Icono',
    habit_archive: 'Quitar de la lista', habit_restore: 'Devolver a la lista',
    archived: 'Archivado', archived_n: 'Archivados: {n}',
    no_habits: 'Aún no hay hábitos',
    no_habits_sub: 'Empieza con dos o tres: es más fácil sostenerlos que diez.',
    add_starter: 'Añadir set inicial',
    starter_added: 'Set de hábitos añadido',
    note_today: 'Nota del día', note_ph: 'Cómo fue el día, qué estorbó, qué salió bien',
    mood: 'Ánimo',
    mood_1: 'Difícil', mood_2: 'Regular', mood_3: 'Normal', mood_4: 'Bien', mood_5: 'Excelente',
    stats_week: 'Esta semana', stats_month: 'Este mes', stats_year: 'Año',
    completion: 'Cumplimiento', calendar: 'Calendario',
    by_habit: 'Por hábito', by_area: 'Por área de vida',
    days_active: 'Días con registros', total_done: 'Total completado',
    perfect_days: 'Días perfectos', perfect_days_hint: 'Días con todo lo planeado hecho',
    no_stats: 'Aún hay pocos datos',
    no_stats_sub: 'Marca tus hábitos unos días y aquí aparecerán gráficas y rachas.',
    reminders: 'Recordatorios', reminders_on: 'Recordarme los hábitos',
    reminder_time: 'A qué hora', reminders_denied: 'Las notificaciones están bloqueadas en el teléfono',
    reminders_ios: 'En iPhone los recordatorios llegan solo si la app está en la pantalla de inicio.',
    reminders_hint: 'El recordatorio llega mientras la app está abierta o en segundo plano.',
    week_start: 'La semana empieza en', ws_mon: 'Lunes', ws_sun: 'Domingo',
    backup: 'Copia de seguridad',
    backup_hint: 'Los datos solo están en este teléfono. Haz una copia cada mes.',
    of_n: 'de {n}',
    times_week: '{n}× por semana',
    done_n_times: 'Completado {n} veces',
    tap_to_add: 'Pulsa para añadir',
    mon: 'Lun', tue: 'Mar', wed: 'Mié', thu: 'Jue', fri: 'Vie', sat: 'Sáb', sun: 'Dom',
  },

  en: {
    app_name: 'Ritmo',
    tab_today: 'Today', tab_habits: 'Habits', tab_stats: 'Progress', tab_settings: 'More',
    cat_body: 'Body', cat_mind: 'Mind', cat_health: 'Health', cat_work: 'Work',
    when_morning: 'Morning', when_day: 'Afternoon', when_evening: 'Evening', when_any: 'Anytime',
    day_progress: 'Day complete', all_done: 'Everything for today is done',
    all_done_sub: 'Keep it up. Tomorrow, another round.',
    nothing_today: 'Nothing planned for today',
    nothing_today_sub: 'Add a habit or enable it for this weekday.',
    streak: 'Streak', streak_days: 'days in a row', best_streak: 'Best streak',
    done_today: 'Done today',
    add_habit: 'New habit', edit_habit: 'Habit',
    habit_title: 'What to do', habit_title_ph: 'e.g. read 20 pages',
    habit_cat: 'Life area', habit_when: 'When',
    habit_type: 'How to measure',
    type_check: 'Done / not done', type_count: 'Count',
    habit_unit: 'Unit', habit_unit_ph: 'pages, minutes, glasses',
    habit_target: 'Daily goal',
    habit_freq: 'How often', freq_daily: 'Every day',
    freq_days: 'Days of the week', freq_week: 'Times per week',
    per_week: 'Times per week',
    habit_icon: 'Icon',
    habit_archive: 'Remove from list', habit_restore: 'Return to list',
    archived: 'Archived', archived_n: 'Archived: {n}',
    no_habits: 'No habits yet',
    no_habits_sub: 'Start with two or three — easier to keep than ten.',
    add_starter: 'Add starter set',
    starter_added: 'Starter habits added',
    note_today: 'Note of the day', note_ph: 'How the day went, what got in the way',
    mood: 'How you feel',
    mood_1: 'Rough', mood_2: 'Meh', mood_3: 'OK', mood_4: 'Good', mood_5: 'Great',
    stats_week: 'This week', stats_month: 'This month', stats_year: 'Year',
    completion: 'Completion', calendar: 'Calendar',
    by_habit: 'By habit', by_area: 'By life area',
    days_active: 'Days with records', total_done: 'Total completed',
    perfect_days: 'Perfect days', perfect_days_hint: 'Days when everything planned was done',
    no_stats: 'Not enough data yet',
    no_stats_sub: 'Track for a few days and charts and streaks will appear here.',
    reminders: 'Reminders', reminders_on: 'Remind me about habits',
    reminder_time: 'At what time', reminders_denied: 'Notifications are blocked in phone settings',
    reminders_ios: 'On iPhone reminders arrive only if the app is on the Home Screen.',
    reminders_hint: 'The reminder arrives while the app is open or in the background.',
    week_start: 'Week starts on', ws_mon: 'Monday', ws_sun: 'Sunday',
    backup: 'Backup',
    backup_hint: 'Data lives only on this phone. Make a copy once a month.',
    of_n: 'of {n}',
    times_week: '{n}× per week',
    done_n_times: 'Completed {n} times',
    tap_to_add: 'Tap to add',
    mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun',
  },
};
