export const dict = {
  ru: {
    app_name: 'Milpa',
    tab_home: 'Обзор', tab_tx: 'Операции', tab_reports: 'Отчёты', tab_settings: 'Ещё',

    book_personal: 'Личное', book_empresa: 'Компания',
    book_switch: 'Кошелёк',
    books_title: 'Кошельки',
    books_hint: 'Как называются ваши два учёта — личный и по компании. Названия видны только вам.',

    net_worth: 'Всего на счетах',
    month_income: 'Доходы', month_expense: 'Расходы', month_net: 'Разница',
    accounts: 'Счета', add_account: 'Новый счёт',
    account_name: 'Название счёта', account_type: 'Тип', account_currency: 'Валюта',
    account_opening: 'Начальный остаток',
    acc_cash: 'Наличные', acc_bank: 'Банк', acc_card: 'Карта', acc_savings: 'Накопления',
    account_archived: 'В архиве', archive: 'Убрать в архив', unarchive: 'Вернуть из архива',
    account_currency_locked: 'Валюту нельзя менять: по счёту уже есть операции. Заведите новый счёт в нужной валюте.',
    account_delete_warn: 'Вместе со счётом удалятся все его операции ({n}). Лучше убрать в архив.',

    tx_expense: 'Расход', tx_income: 'Доход', tx_transfer: 'Перевод',
    new_tx: 'Новая операция', edit_tx: 'Операция',
    tx_account: 'Со счёта', tx_account_in: 'На счёт', tx_to_account: 'Куда',
    tx_party: 'Кому / от кого', tx_party_ph: 'Например: OXXO, клиент Иванов',
    tx_note_ph: 'Комментарий (необязательно)',
    tx_received: 'Сумма зачисления',
    no_tx: 'Операций пока нет',
    no_tx_hint: 'Нажмите «плюс», чтобы записать первый расход или доход.',
    no_accounts: 'Сначала создайте счёт',
    no_accounts_hint: 'Счёт — это ваш кошелёк, карта или счёт компании. Без него некуда записывать операции.',

    categories: 'Категории', add_category: 'Новая категория',
    cat_kind: 'Тип', cat_icon: 'Значок',
    cat_in_use: 'Категория используется в {n} операциях — они останутся без категории.',
    uncategorized: 'Без категории',

    recurring: 'Регулярные платежи', add_recurring: 'Новый регулярный платёж',
    rec_freq: 'Как часто', rec_monthly: 'Раз в месяц', rec_weekly: 'Раз в неделю',
    rec_day: 'Число месяца', rec_weekday: 'День недели',
    rec_next: 'Следующий', rec_due: 'Пора провести',
    rec_post: 'Провести', rec_skip: 'Пропустить',
    rec_posted: 'Операция записана',
    rec_active: 'Активен',
    rec_none: 'Регулярных платежей нет',
    rec_none_hint: 'Аренда, зарплаты, подписки — то, что повторяется каждый месяц. Приложение напомнит и запишет одним касанием.',

    report_by_category: 'По категориям', report_by_month: 'По месяцам',
    report_pl: 'Прибыль и убыток', report_cashflow: 'Движение денег',
    report_period: 'Период', period_month: 'Месяц', period_quarter: 'Квартал',
    period_year: 'Год', period_all: 'Всё время',
    profit: 'Прибыль', loss: 'Убыток',
    avg_month: 'В среднем за месяц', biggest: 'Крупнейшие расходы',
    no_data_period: 'За этот период операций нет',

    fx: 'Курс валют', fx_rate: 'Сколько песо за 1 доллар',
    fx_hint: 'Используется, чтобы свести счета в разных валютах в один итог.',
    fx_updated: 'Обновлён {d}', fx_never: 'Задан вручную',
    base_currency: 'Основная валюта', base_hint: 'В ней показываются общие итоги.',

    export_csv: 'Выгрузить операции в таблицу (CSV)',
    csv_hint: 'Откроется в Excel или Google Таблицах.',
    backup: 'Резервная копия',
    backup_hint: 'Данные хранятся только на этом телефоне. Делайте копию раз в месяц.',

    of_total: '{p}% от расходов',
    n_ops: '{n} оп.',
    balance_in_base: '≈ {v} в {c}',
    this_month: 'Этот месяц',
    since_start: 'С начала месяца',
    spent_today: 'Сегодня потрачено',
    left_this_month: 'Разница за месяц',
    top_categories: 'Куда уходят деньги',
    recent: 'Последние операции',
    see_all: 'Все',
    amount_required: 'Введите сумму больше нуля',
    same_account: 'Выберите разные счета',
  },

  es: {
    app_name: 'Milpa',
    tab_home: 'Resumen', tab_tx: 'Movimientos', tab_reports: 'Reportes', tab_settings: 'Más',
    book_personal: 'Personal', book_empresa: 'Empresa', book_switch: 'Cartera',
    books_title: 'Carteras',
    books_hint: 'Cómo se llaman tus dos contabilidades: la personal y la de la empresa.',
    net_worth: 'Total en cuentas',
    month_income: 'Ingresos', month_expense: 'Gastos', month_net: 'Diferencia',
    accounts: 'Cuentas', add_account: 'Nueva cuenta',
    account_name: 'Nombre de la cuenta', account_type: 'Tipo', account_currency: 'Moneda',
    account_opening: 'Saldo inicial',
    acc_cash: 'Efectivo', acc_bank: 'Banco', acc_card: 'Tarjeta', acc_savings: 'Ahorros',
    account_archived: 'Archivada', archive: 'Archivar', unarchive: 'Restaurar',
    account_currency_locked: 'No se puede cambiar la moneda: la cuenta ya tiene movimientos.',
    account_delete_warn: 'Se eliminarán también sus {n} movimientos. Mejor archívala.',
    tx_expense: 'Gasto', tx_income: 'Ingreso', tx_transfer: 'Traspaso',
    new_tx: 'Nuevo movimiento', edit_tx: 'Movimiento',
    tx_account: 'Desde', tx_account_in: 'A la cuenta', tx_to_account: 'Hacia',
    tx_party: 'A quién / de quién', tx_party_ph: 'Ej.: OXXO, cliente Pérez',
    tx_note_ph: 'Comentario (opcional)',
    tx_received: 'Importe recibido',
    no_tx: 'Aún no hay movimientos',
    no_tx_hint: 'Pulsa «+» para registrar tu primer gasto o ingreso.',
    no_accounts: 'Primero crea una cuenta',
    no_accounts_hint: 'Una cuenta es tu efectivo, tarjeta o cuenta de la empresa.',
    categories: 'Categorías', add_category: 'Nueva categoría',
    cat_kind: 'Tipo', cat_icon: 'Icono',
    cat_in_use: 'La categoría se usa en {n} movimientos; quedarán sin categoría.',
    uncategorized: 'Sin categoría',
    recurring: 'Pagos recurrentes', add_recurring: 'Nuevo pago recurrente',
    rec_freq: 'Frecuencia', rec_monthly: 'Cada mes', rec_weekly: 'Cada semana',
    rec_day: 'Día del mes', rec_weekday: 'Día de la semana',
    rec_next: 'Próximo', rec_due: 'Toca registrarlo',
    rec_post: 'Registrar', rec_skip: 'Omitir',
    rec_posted: 'Movimiento registrado',
    rec_active: 'Activo',
    rec_none: 'No hay pagos recurrentes',
    rec_none_hint: 'Renta, sueldos, suscripciones: lo que se repite cada mes.',
    report_by_category: 'Por categoría', report_by_month: 'Por mes',
    report_pl: 'Pérdidas y ganancias', report_cashflow: 'Flujo de efectivo',
    report_period: 'Periodo', period_month: 'Mes', period_quarter: 'Trimestre',
    period_year: 'Año', period_all: 'Todo',
    profit: 'Utilidad', loss: 'Pérdida',
    avg_month: 'Promedio mensual', biggest: 'Mayores gastos',
    no_data_period: 'Sin movimientos en este periodo',
    fx: 'Tipo de cambio', fx_rate: 'Pesos por 1 dólar',
    fx_hint: 'Sirve para sumar cuentas en distintas monedas.',
    fx_updated: 'Actualizado {d}', fx_never: 'Definido a mano',
    base_currency: 'Moneda principal', base_hint: 'En ella se muestran los totales.',
    export_csv: 'Exportar movimientos (CSV)',
    csv_hint: 'Se abre en Excel o Google Sheets.',
    backup: 'Copia de seguridad',
    backup_hint: 'Los datos solo están en este teléfono. Haz una copia cada mes.',
    of_total: '{p}% de los gastos',
    n_ops: '{n} mov.',
    balance_in_base: '≈ {v} en {c}',
    this_month: 'Este mes', since_start: 'Desde el inicio del mes',
    spent_today: 'Gastado hoy', left_this_month: 'Diferencia del mes',
    top_categories: 'A dónde se va el dinero', recent: 'Últimos movimientos',
    see_all: 'Todos',
    amount_required: 'Introduce un importe mayor que cero',
    same_account: 'Elige cuentas distintas',
  },

  en: {
    app_name: 'Milpa',
    tab_home: 'Overview', tab_tx: 'Transactions', tab_reports: 'Reports', tab_settings: 'More',
    book_personal: 'Personal', book_empresa: 'Business', book_switch: 'Wallet',
    books_title: 'Wallets',
    books_hint: 'What your two sets of books are called — personal and business.',
    net_worth: 'Total across accounts',
    month_income: 'Income', month_expense: 'Expenses', month_net: 'Difference',
    accounts: 'Accounts', add_account: 'New account',
    account_name: 'Account name', account_type: 'Type', account_currency: 'Currency',
    account_opening: 'Opening balance',
    acc_cash: 'Cash', acc_bank: 'Bank', acc_card: 'Card', acc_savings: 'Savings',
    account_archived: 'Archived', archive: 'Archive', unarchive: 'Restore',
    account_currency_locked: 'Currency cannot change: the account already has transactions.',
    account_delete_warn: 'Its {n} transactions will be deleted too. Archiving is safer.',
    tx_expense: 'Expense', tx_income: 'Income', tx_transfer: 'Transfer',
    new_tx: 'New transaction', edit_tx: 'Transaction',
    tx_account: 'From', tx_account_in: 'To account', tx_to_account: 'To',
    tx_party: 'To / from whom', tx_party_ph: 'e.g. OXXO, client Smith',
    tx_note_ph: 'Note (optional)',
    tx_received: 'Amount received',
    no_tx: 'No transactions yet',
    no_tx_hint: 'Tap the plus button to record your first expense or income.',
    no_accounts: 'Create an account first',
    no_accounts_hint: 'An account is your cash, card or company account.',
    categories: 'Categories', add_category: 'New category',
    cat_kind: 'Type', cat_icon: 'Icon',
    cat_in_use: 'This category is used in {n} transactions — they will lose it.',
    uncategorized: 'Uncategorized',
    recurring: 'Recurring payments', add_recurring: 'New recurring payment',
    rec_freq: 'How often', rec_monthly: 'Monthly', rec_weekly: 'Weekly',
    rec_day: 'Day of month', rec_weekday: 'Weekday',
    rec_next: 'Next', rec_due: 'Due now',
    rec_post: 'Record', rec_skip: 'Skip',
    rec_posted: 'Transaction recorded',
    rec_active: 'Active',
    rec_none: 'No recurring payments',
    rec_none_hint: 'Rent, salaries, subscriptions — whatever repeats every month.',
    report_by_category: 'By category', report_by_month: 'By month',
    report_pl: 'Profit and loss', report_cashflow: 'Cash flow',
    report_period: 'Period', period_month: 'Month', period_quarter: 'Quarter',
    period_year: 'Year', period_all: 'All time',
    profit: 'Profit', loss: 'Loss',
    avg_month: 'Monthly average', biggest: 'Largest expenses',
    no_data_period: 'No transactions in this period',
    fx: 'Exchange rate', fx_rate: 'Pesos per 1 dollar',
    fx_hint: 'Used to combine accounts in different currencies into one total.',
    fx_updated: 'Updated {d}', fx_never: 'Set manually',
    base_currency: 'Main currency', base_hint: 'Totals are shown in it.',
    export_csv: 'Export transactions (CSV)',
    csv_hint: 'Opens in Excel or Google Sheets.',
    backup: 'Backup',
    backup_hint: 'Data lives only on this phone. Make a copy once a month.',
    of_total: '{p}% of expenses',
    n_ops: '{n} txn',
    balance_in_base: '≈ {v} in {c}',
    this_month: 'This month', since_start: 'Since start of month',
    spent_today: 'Spent today', left_this_month: 'Difference this month',
    top_categories: 'Where money goes', recent: 'Recent transactions',
    see_all: 'All',
    amount_required: 'Enter an amount greater than zero',
    same_account: 'Choose two different accounts',
  },
};

/* Раздел «Зарплата и налоги» — вынесен отдельно, чтобы не раздувать
   основной словарь и было видно, что относится к налоговому расчёту. */
const nomina = {
  ru: {
    nom_title: 'Зарплата и налоги',
    nom_menu: 'Зарплата и налоги',
    nom_from_net: 'От «на руки»', nom_from_gross: 'От брутто',
    nom_net_hint: 'сколько получает на руки, песо в месяц',
    nom_gross_hint: 'оклад до налогов, песо в месяц',

    nom_nomina: 'Nómina + IMSS', nom_asimilados: 'Asimilados',
    nom_resico: 'RESICO', nom_dividendos: 'Дивиденды',

    nom_resico_blocked: 'Совладелец компании не может быть в RESICO (ст. 113-E LISR). Для собственника Koshtur этот режим закрыт — показан только для сравнения.',
    nom_resico_cap: 'Превышен годовой потолок RESICO ({v}) — SAT переведёт на общий режим.',

    nom_breakdown: 'Что получает Кира',
    nom_gross: 'Начислено (брутто)',
    nom_isr: 'ISR удержан',
    nom_isr_corp: 'Налог на прибыль + удержание с дивидендов',
    nom_imss_employee: 'Взносы IMSS с работника',
    nom_net: 'На руки',

    nom_company_side: 'Что платит компания',
    nom_imss_employer: 'Взносы IMSS работодателя',
    nom_isn: 'Налог на фонд оплаты труда ({s})',
    nom_company_cash: 'Уходит со счёта компании',
    nom_shield: 'Экономия на налоге на прибыль',
    nom_true_cost: 'Реально стоит компании',

    nom_savings: 'Из этого — накопления Киры',
    nom_savings_hint: 'Retiro, cesantía и INFONAVIT — это не налог. Деньги идут на её Afore и жилищный субсчёт и остаются её деньгами.',

    nom_annual: 'Дополнительно раз в год',
    nom_aguinaldo: 'Агинальдо (15 дней)',
    nom_prima: 'Отпускная премия',

    nom_compare: 'Сравнение режимов',
    nom_per_peso: '{v} песо затрат на 1 песо на руки',
    nom_per_month: 'в месяц',
    nom_not_available: 'недоступен совладельцу',

    nom_isn_state: 'Штат для налога на фонд оплаты труда',
    nom_sources: 'Источники ставок',
    nom_disclaimer: 'Расчёт для планирования. Декларации подаёт бухгалтер — ставку riesgo de trabajo, класс предприятия и применимость налога к asimilados подтвердите у него.',
    nom_checked: 'Ставки {y} года, сверены {d}',

    nom_record: 'Записать в учёт за этот месяц',
    nom_recorded: 'Записано: расход компании и доход в личном кошельке',
    nom_tx_net: 'Зарплата Кире, на руки',
    nom_tx_taxes: 'Налоги и взносы с зарплаты',
    nom_tx_income: 'Зарплата от {v}',
  },
  es: {
    nom_title: 'Sueldo e impuestos', nom_menu: 'Sueldo e impuestos',
    nom_from_net: 'Desde el neto', nom_from_gross: 'Desde el bruto',
    nom_net_hint: 'cuánto recibe libre, pesos al mes',
    nom_gross_hint: 'sueldo antes de impuestos, pesos al mes',
    nom_nomina: 'Nómina + IMSS', nom_asimilados: 'Asimilados',
    nom_resico: 'RESICO', nom_dividendos: 'Dividendos',
    nom_resico_blocked: 'Un socio o accionista no puede tributar en RESICO (art. 113-E LISR). Se muestra solo para comparar.',
    nom_resico_cap: 'Se rebasa el tope anual de RESICO ({v}); el SAT cambia al régimen general.',
    nom_breakdown: 'Lo que recibe',
    nom_gross: 'Percepción bruta', nom_isr: 'ISR retenido',
    nom_isr_corp: 'ISR corporativo + retención de dividendos',
    nom_imss_employee: 'Cuotas IMSS del trabajador', nom_net: 'Neto',
    nom_company_side: 'Lo que paga la empresa',
    nom_imss_employer: 'Cuotas IMSS patronales',
    nom_isn: 'Impuesto sobre nóminas ({s})',
    nom_company_cash: 'Sale de la cuenta de la empresa',
    nom_shield: 'Ahorro en ISR corporativo',
    nom_true_cost: 'Costo real para la empresa',
    nom_savings: 'De eso, ahorro propio',
    nom_savings_hint: 'Retiro, cesantía e INFONAVIT no son impuesto: van a su Afore y subcuenta de vivienda.',
    nom_annual: 'Adicional una vez al año',
    nom_aguinaldo: 'Aguinaldo (15 días)', nom_prima: 'Prima vacacional',
    nom_compare: 'Comparación de regímenes',
    nom_per_peso: '{v} de costo por cada peso neto',
    nom_per_month: 'al mes', nom_not_available: 'no disponible para socios',
    nom_isn_state: 'Estado para el ISN', nom_sources: 'Fuentes de las tasas',
    nom_disclaimer: 'Cálculo para planeación. Las declaraciones las presenta el contador: confirma con él la prima de riesgo de trabajo y la aplicación del ISN a asimilados.',
    nom_checked: 'Tasas {y}, verificadas el {d}',
    nom_record: 'Registrar este mes',
    nom_recorded: 'Registrado en empresa y en personal',
    nom_tx_net: 'Sueldo neto', nom_tx_taxes: 'Impuestos y cuotas sobre nómina',
    nom_tx_income: 'Sueldo de {v}',
  },
  en: {
    nom_title: 'Salary and taxes', nom_menu: 'Salary and taxes',
    nom_from_net: 'From net', nom_from_gross: 'From gross',
    nom_net_hint: 'take-home per month, pesos',
    nom_gross_hint: 'salary before tax, pesos per month',
    nom_nomina: 'Payroll + IMSS', nom_asimilados: 'Asimilados',
    nom_resico: 'RESICO', nom_dividendos: 'Dividends',
    nom_resico_blocked: 'A shareholder cannot use RESICO (art. 113-E LISR). Shown for comparison only.',
    nom_resico_cap: 'RESICO annual cap ({v}) exceeded — SAT moves you to the general regime.',
    nom_breakdown: 'What she receives',
    nom_gross: 'Gross', nom_isr: 'ISR withheld',
    nom_isr_corp: 'Corporate tax + dividend withholding',
    nom_imss_employee: 'Employee IMSS contributions', nom_net: 'Take-home',
    nom_company_side: 'What the company pays',
    nom_imss_employer: 'Employer IMSS contributions',
    nom_isn: 'State payroll tax ({s})',
    nom_company_cash: 'Leaves the company account',
    nom_shield: 'Corporate tax saved',
    nom_true_cost: 'Real cost to the company',
    nom_savings: 'Of that, her own savings',
    nom_savings_hint: 'Retiro, cesantía and INFONAVIT are not tax — they go to her Afore and housing subaccount.',
    nom_annual: 'Additionally once a year',
    nom_aguinaldo: 'Aguinaldo (15 days)', nom_prima: 'Vacation premium',
    nom_compare: 'Regime comparison',
    nom_per_peso: '{v} of cost per peso taken home',
    nom_per_month: 'per month', nom_not_available: 'not available to shareholders',
    nom_isn_state: 'State for payroll tax', nom_sources: 'Rate sources',
    nom_disclaimer: 'Planning calculation. Your accountant files the returns — confirm the work-risk premium and whether the payroll tax applies to asimilados.',
    nom_checked: '{y} rates, verified {d}',
    nom_record: 'Record for this month',
    nom_recorded: 'Recorded in business and personal books',
    nom_tx_net: 'Net salary', nom_tx_taxes: 'Payroll taxes and contributions',
    nom_tx_income: 'Salary from {v}',
  },
};

for (const lang of Object.keys(dict)) Object.assign(dict[lang], nomina[lang]);

/* Вкладка «Новости» и автоматический курс. */
const news = {
  ru: {
    tab_news: 'Новости',
    news_fx: 'Курс доллара',
    news_fx_unit: 'песо за 1 доллар',
    news_fx_unofficial: 'рыночный, не официальный',
    news_fx_manual: 'В расчётах используется ваш курс: {v}',
    news_refresh: 'Обновить',
    news_loading: 'Загружаю новости',
    news_none: 'Новостей пока нет',
    news_none_hint: 'Лента обновляется раз в сутки. Проверьте подключение к интернету.',
    news_offline: 'Нет связи — показаны последние сохранённые новости',
    news_updated: 'Обновлено {d} в {h}',
    news_sources_note: 'Заголовки и ссылки на издания. Полные тексты открываются на их сайтах.',
    fx_auto: 'Обновлять курс автоматически',
    fx_auto_hint: 'Курс берётся раз в сутки вместе с новостями. Если введёте свой — автоматическое обновление отключится.',
    fx_official_hint: 'Для официального курса Banxico (FIX) нужен бесплатный токен — скажите, и я подключу.',
  },
  es: {
    tab_news: 'Noticias',
    news_fx: 'Tipo de cambio',
    news_fx_unit: 'pesos por dólar',
    news_fx_unofficial: 'de mercado, no oficial',
    news_fx_manual: 'En los cálculos se usa tu tipo de cambio: {v}',
    news_refresh: 'Actualizar',
    news_loading: 'Cargando noticias',
    news_none: 'Aún no hay noticias',
    news_none_hint: 'La lista se actualiza una vez al día. Revisa tu conexión.',
    news_offline: 'Sin conexión: se muestran las últimas noticias guardadas',
    news_updated: 'Actualizado el {d} a las {h}',
    news_sources_note: 'Titulares y enlaces a los medios. Los textos completos se abren en sus sitios.',
    fx_auto: 'Actualizar el tipo de cambio solo',
    fx_auto_hint: 'Se toma una vez al día junto con las noticias. Si escribes el tuyo, se desactiva.',
    fx_official_hint: 'Para el tipo de cambio oficial de Banxico (FIX) hace falta un token gratuito.',
  },
  en: {
    tab_news: 'News',
    news_fx: 'Exchange rate',
    news_fx_unit: 'pesos per dollar',
    news_fx_unofficial: 'market rate, not official',
    news_fx_manual: 'Calculations use your own rate: {v}',
    news_refresh: 'Refresh',
    news_loading: 'Loading news',
    news_none: 'No news yet',
    news_none_hint: 'The feed updates once a day. Check your connection.',
    news_offline: 'Offline — showing the last saved news',
    news_updated: 'Updated {d} at {h}',
    news_sources_note: 'Headlines and links to publishers. Full articles open on their sites.',
    fx_auto: 'Update the rate automatically',
    fx_auto_hint: 'Taken once a day together with the news. Entering your own switches it off.',
    fx_official_hint: 'The official Banxico (FIX) rate needs a free token.',
  },
};

for (const lang of Object.keys(dict)) Object.assign(dict[lang], news[lang]);

/* Загрузка банковских выписок. */
const imports = {
  ru: {
    imp_title: 'Загрузить выписку', imp_menu: 'Загрузить выписку',
    imp_intro: 'Загрузите сюда выписку из банка или архив счетов-фактур из SAT — подойдут CSV, TXT, ZIP, PDF и XML. Прежде чем что-то записать, приложение покажет, что именно оно разобрало.',
    imp_where: 'BBVA: бизнес-счета выгружают CSV и TXT, личные — PDF. PDF читается распознаванием, поэтому для него нужен ключ доступа и он стоит несколько песо за выписку.',
    imp_choose: 'Выбрать файл', imp_other_file: 'Другой файл',
    imp_rows: 'строк с данными: {n}',
    imp_account: 'На какой счёт',
    imp_columns: 'Какая колонка за что отвечает',
    imp_desc: 'Описание',
    imp_amount_mode: 'Как записана сумма',
    imp_one_column: 'Одной колонкой', imp_two_columns: 'Приход и расход',
    imp_debit: 'Списание', imp_credit: 'Поступление', imp_amount_col: 'Сумма',
    imp_date_order: 'Порядок в дате',
    imp_new: 'Новых', imp_dupes: 'Повторы', imp_skipped: 'Пропущено',
    imp_preview: 'Что будет записано',
    imp_and_more: 'и ещё {n}',
    imp_skipped_hint: 'Эти строки пропущены — в них не нашлось даты или суммы:',
    imp_nothing_parsed: 'Ни одной операции не разобралось. Проверьте, правильно ли выбраны колонки.',
    imp_nothing_to_add: 'Нечего добавлять',
    imp_do: 'Записать операций: {n}',
    imp_done: 'Записано операций: {n}',
    imp_empty: 'Файл пустой или не читается',
    imp_col: 'Колонка {n}',
  },
  es: {
    imp_title: 'Importar estado de cuenta', imp_menu: 'Importar estado de cuenta',
    imp_intro: 'Sube aquí tu estado de cuenta o el ZIP de CFDI del SAT: CSV, TXT, ZIP, PDF o XML. Antes de guardar nada verás qué se reconoció.',
    imp_where: 'BBVA: las cuentas empresariales exportan CSV y TXT; las personales, PDF. El PDF se lee con reconocimiento y requiere clave.',
    imp_choose: 'Elegir archivo', imp_other_file: 'Otro archivo',
    imp_rows: 'filas con datos: {n}',
    imp_account: 'A qué cuenta',
    imp_columns: 'Qué columna es cuál',
    imp_desc: 'Descripción',
    imp_amount_mode: 'Cómo viene el importe',
    imp_one_column: 'Una columna', imp_two_columns: 'Cargo y abono',
    imp_debit: 'Cargo', imp_credit: 'Abono', imp_amount_col: 'Importe',
    imp_date_order: 'Orden de la fecha',
    imp_new: 'Nuevos', imp_dupes: 'Repetidos', imp_skipped: 'Omitidos',
    imp_preview: 'Lo que se va a guardar',
    imp_and_more: 'y {n} más',
    imp_skipped_hint: 'Estas filas se omitieron: no se encontró fecha o importe:',
    imp_nothing_parsed: 'No se reconoció ningún movimiento. Revisa las columnas elegidas.',
    imp_nothing_to_add: 'Nada que agregar',
    imp_do: 'Guardar {n} movimientos',
    imp_done: 'Movimientos guardados: {n}',
    imp_empty: 'El archivo está vacío o no se puede leer',
    imp_col: 'Columna {n}',
  },
  en: {
    imp_title: 'Import statement', imp_menu: 'Import statement',
    imp_intro: 'Upload a bank statement or your SAT invoice archive — CSV, TXT, ZIP, PDF or XML. Before anything is saved you see what was recognised.',
    imp_where: 'BBVA: business accounts export CSV and TXT, personal ones PDF. PDFs are read by recognition and need an API key.',
    imp_choose: 'Choose file', imp_other_file: 'Another file',
    imp_rows: 'data rows: {n}',
    imp_account: 'Into which account',
    imp_columns: 'Which column is which',
    imp_desc: 'Description',
    imp_amount_mode: 'How the amount is written',
    imp_one_column: 'One column', imp_two_columns: 'Debit and credit',
    imp_debit: 'Debit', imp_credit: 'Credit', imp_amount_col: 'Amount',
    imp_date_order: 'Date order',
    imp_new: 'New', imp_dupes: 'Duplicates', imp_skipped: 'Skipped',
    imp_preview: 'What will be saved',
    imp_and_more: 'and {n} more',
    imp_skipped_hint: 'These rows were skipped — no date or amount found:',
    imp_nothing_parsed: 'No transactions were recognised. Check the selected columns.',
    imp_nothing_to_add: 'Nothing to add',
    imp_do: 'Save {n} transactions',
    imp_done: 'Transactions saved: {n}',
    imp_empty: 'The file is empty or unreadable',
    imp_col: 'Column {n}',
  },
};

for (const lang of Object.keys(dict)) Object.assign(dict[lang], imports[lang]);

/* Распознавание чеков. */
const ai = {
  ru: {
    ai_title: 'Распознавание чеков',
    ai_what: 'Сфотографируйте чек, счёт или экран перевода — приложение прочитает сумму, дату и продавца и заполнит форму. Записываете всё равно вы, после проверки.',
    ai_key: 'Ключ доступа',
    ai_test: 'Проверить', ai_testing: 'Проверяю…', ai_key_ok: 'Ключ работает',
    ai_forget: 'Забыть ключ',
    ai_cost: 'Каждый снимок стоит примерно 30–40 сентаво. Оплата идёт по вашему ключу напрямую в Anthropic — в приложении подписки нет.',
    ai_privacy: 'Снимок уходит в Anthropic для распознавания и там не сохраняется. Ключ хранится только на этом устройстве и НЕ попадает в резервные копии.',
    ai_where_key: 'Ключ берётся на console.anthropic.com → API keys. Нужен платёжный метод, отдельный от подписки на Claude.',

    ai_scan: 'Заполнить по фото',
    ai_reading: 'Читаю чек…',
    ai_filled: 'Готово — проверьте и сохраните',
    ai_filled_check: 'Заполнено, но снимок читался плохо — проверьте сумму и дату',
    ai_unreadable: 'Не удалось разобрать: похоже, это не чек и не платёжный документ',
    ai_currency_mismatch: 'В документе валюта {c}, а подходящего счёта нет — проверьте сумму',

    ai_no_key: 'Сначала укажите ключ доступа в «Ещё» → «Распознавание чеков»',
    ai_bad_key: 'Ключ не принят — проверьте, что скопировали его целиком',
    ai_rate_limit: 'Слишком часто — подождите минуту и попробуйте снова',
    ai_network: 'Нет связи с сервером распознавания',
    ai_server: 'Сервер распознавания временно недоступен',
    ai_refused: 'Распознавание отклонено — попробуйте другой снимок',
    ai_bad_answer: 'Ответ пришёл в неожиданном виде',
    ai_bad_request: 'Запрос отклонён — возможно, снимок слишком большой',
    ai_failed: 'Не получилось распознать',
  },
  es: {
    ai_title: 'Lectura de tickets',
    ai_what: 'Toma una foto del ticket, la factura o la pantalla de transferencia: la app lee el importe, la fecha y el comercio y llena el formulario. Guardar lo haces tú.',
    ai_key: 'Clave de acceso',
    ai_test: 'Probar', ai_testing: 'Probando…', ai_key_ok: 'La clave funciona',
    ai_forget: 'Olvidar clave',
    ai_cost: 'Cada foto cuesta unos 30–40 centavos, cobrados directamente por Anthropic con tu clave.',
    ai_privacy: 'La foto se envía a Anthropic para leerla y no se guarda ahí. La clave vive solo en este dispositivo y NO entra en las copias de seguridad.',
    ai_where_key: 'La clave se obtiene en console.anthropic.com → API keys.',
    ai_scan: 'Llenar con una foto',
    ai_reading: 'Leyendo el ticket…',
    ai_filled: 'Listo: revisa y guarda',
    ai_filled_check: 'Llenado, pero la foto se leía mal: revisa importe y fecha',
    ai_unreadable: 'No se pudo leer: no parece un documento de pago',
    ai_currency_mismatch: 'El documento está en {c} y no hay cuenta en esa moneda',
    ai_no_key: 'Primero pon tu clave en «Más» → «Lectura de tickets»',
    ai_bad_key: 'Clave rechazada: revisa que la copiaste completa',
    ai_rate_limit: 'Demasiadas peticiones: espera un minuto',
    ai_network: 'Sin conexión con el servicio de lectura',
    ai_server: 'El servicio de lectura no está disponible',
    ai_refused: 'Lectura rechazada: prueba con otra foto',
    ai_bad_answer: 'La respuesta llegó en un formato inesperado',
    ai_bad_request: 'Petición rechazada: quizá la foto es muy grande',
    ai_failed: 'No se pudo leer',
  },
  en: {
    ai_title: 'Receipt reading',
    ai_what: 'Photograph a receipt, invoice or transfer screen — the app reads the amount, date and merchant and fills the form. You still save it yourself.',
    ai_key: 'API key',
    ai_test: 'Test', ai_testing: 'Testing…', ai_key_ok: 'The key works',
    ai_forget: 'Forget key',
    ai_cost: 'Each photo costs roughly 2 US cents, billed directly by Anthropic to your key.',
    ai_privacy: 'The photo goes to Anthropic to be read and is not stored there. The key lives only on this device and is NOT included in backups.',
    ai_where_key: 'Get a key at console.anthropic.com → API keys.',
    ai_scan: 'Fill from a photo',
    ai_reading: 'Reading the receipt…',
    ai_filled: 'Done — check it and save',
    ai_filled_check: 'Filled, but the photo was hard to read — check amount and date',
    ai_unreadable: 'Could not read it: this does not look like a payment document',
    ai_currency_mismatch: 'The document is in {c} and there is no account in that currency',
    ai_no_key: 'Add your API key first in «More» → «Receipt reading»',
    ai_bad_key: 'Key rejected — check you copied all of it',
    ai_rate_limit: 'Too many requests — wait a minute',
    ai_network: 'No connection to the reading service',
    ai_server: 'The reading service is unavailable',
    ai_refused: 'Reading was declined — try another photo',
    ai_bad_answer: 'The answer came back in an unexpected shape',
    ai_bad_request: 'Request rejected — the photo may be too large',
    ai_failed: 'Could not read it',
  },
};

for (const lang of Object.keys(dict)) Object.assign(dict[lang], ai[lang]);

/* Архивы и неподдерживаемые форматы выписок. */
const archives = {
  ru: {
    imp_which_file: 'Какой файл из архива',
    imp_which_hint: 'В архиве несколько таблиц — выберите ту, где движения по счёту.',
    imp_zip_empty: 'В архиве нет таблицы CSV или TXT. Внутри: {files}',
    imp_zip_bad: 'Архив не читается — возможно, он повреждён или защищён паролем',
    imp_zip_old: 'Браузер слишком старый, чтобы открыть архив. Распакуйте его на телефоне и загрузите файл из него.',
    imp_pdf: 'Это PDF — из него выписку пока не прочитать. В интернет-банке BBVA для бизнес-счёта выберите формат CSV или TXT.',
    imp_excel: 'Это файл Excel. Откройте его и сохраните как CSV — тогда загрузится.',
  },
  es: {
    imp_which_file: 'Qué archivo del ZIP',
    imp_which_hint: 'El archivo trae varias tablas: elige la de los movimientos.',
    imp_zip_empty: 'El ZIP no trae un CSV ni un TXT. Contiene: {files}',
    imp_zip_bad: 'No se pudo abrir el archivo: puede estar dañado o con contraseña',
    imp_zip_old: 'El navegador es muy antiguo para abrir el ZIP. Descomprímelo y sube el archivo de dentro.',
    imp_pdf: 'Es un PDF y todavía no se puede leer. En la banca en línea elige formato CSV o TXT.',
    imp_excel: 'Es un archivo de Excel. Ábrelo y guárdalo como CSV.',
  },
  en: {
    imp_which_file: 'Which file from the archive',
    imp_which_hint: 'The archive holds several tables — pick the one with the transactions.',
    imp_zip_empty: 'No CSV or TXT inside the archive. It contains: {files}',
    imp_zip_bad: 'The archive could not be opened — it may be damaged or password-protected',
    imp_zip_old: 'This browser is too old to open archives. Unpack it and upload the file inside.',
    imp_pdf: 'This is a PDF and cannot be read yet. In online banking choose CSV or TXT instead.',
    imp_excel: 'This is an Excel file. Open it and save as CSV.',
  },
};

for (const lang of Object.keys(dict)) Object.assign(dict[lang], archives[lang]);

/* Чтение выписки в PDF. */
const pdfImport = {
  ru: {
    imp_pdf_no_key: 'Чтобы читать PDF, укажите ключ в «Ещё» → «Распознавание чеков»',
    imp_pdf_big: 'Файл слишком большой. Выгрузите выписку за меньший период.',
    imp_pdf_reading: 'Читаю выписку',
    imp_pdf_wait: 'Многостраничная выписка может занять минуту. Не закрывайте экран.',
    imp_pdf_nothing: 'В этом PDF не нашлось операций — похоже, это не выписка по счёту',
    imp_pdf_check: 'Проверьте список: снимите отметку с того, что записывать не нужно. Строки, помеченные как неуверенные, стоит сверить с выпиской.',
    imp_found: 'Найдено', imp_chosen: 'Отмечено',
    imp_already: 'уже есть', imp_unsure: 'читалось плохо',
    imp_all: 'Отметить все', imp_none: 'Снять все',
    ai_too_long: 'Выписка слишком длинная — выгрузите за меньший период',
  },
  es: {
    imp_pdf_no_key: 'Para leer PDF pon tu clave en «Más» → «Lectura de tickets»',
    imp_pdf_big: 'El archivo es muy grande. Descarga un periodo más corto.',
    imp_pdf_reading: 'Leyendo el estado de cuenta',
    imp_pdf_wait: 'Un estado de varias páginas puede tardar un minuto.',
    imp_pdf_nothing: 'No se encontraron movimientos: no parece un estado de cuenta',
    imp_pdf_check: 'Revisa la lista y desmarca lo que no quieras guardar.',
    imp_found: 'Encontrados', imp_chosen: 'Marcados',
    imp_already: 'ya existe', imp_unsure: 'poco legible',
    imp_all: 'Marcar todo', imp_none: 'Desmarcar todo',
    ai_too_long: 'El estado de cuenta es muy largo: usa un periodo más corto',
  },
  en: {
    imp_pdf_no_key: 'To read PDFs add your key in «More» → «Receipt reading»',
    imp_pdf_big: 'The file is too large. Export a shorter period.',
    imp_pdf_reading: 'Reading the statement',
    imp_pdf_wait: 'A multi-page statement can take a minute.',
    imp_pdf_nothing: 'No transactions found — this does not look like a bank statement',
    imp_pdf_check: 'Check the list and untick anything you do not want saved.',
    imp_found: 'Found', imp_chosen: 'Ticked',
    imp_already: 'already there', imp_unsure: 'hard to read',
    imp_all: 'Tick all', imp_none: 'Untick all',
    ai_too_long: 'The statement is too long — export a shorter period',
  },
};

for (const lang of Object.keys(dict)) Object.assign(dict[lang], pdfImport[lang]);

/* Цели накопления. */
const goals = {
  ru: {
    goal_title: 'Цели и накопления',
    goal_new: 'Новая цель',
    goal_name: 'На что копим', goal_name_ph: 'Например: отпуск, подушка, машина',
    goal_target: 'Сколько нужно',
    goal_deadline: 'К какому числу',
    goal_deadline_hint: 'Можно не указывать — тогда просто копим без срока.',
    goal_account: 'Где лежат деньги',
    goal_account_none: 'Отмечать вручную',
    goal_account_auto: 'Накопленным считается остаток на этом счёте — отмечать ничего не нужно.',
    goal_account_manual: 'Вы сами отмечаете, сколько отложили. На остатки по счетам это не влияет.',
    goal_of: 'из',
    goal_left: 'осталось {v}',
    goal_per_month: 'по {v} в месяц',
    goal_per_month_short: 'В месяц',
    goal_done: 'Цель достигнута',
    goal_overdue: 'срок прошёл',
    goal_put: 'Отложить',
    goal_delete_saving: 'Накопленное по цели уменьшится на эту сумму.',
    goal_added: 'Отложено',
    goal_history: 'Когда откладывали',
    goal_saving_note_ph: 'Откуда отложили (необязательно)',
    goal_saving_hint: 'Это пометка, а не перевод: остатки на счетах не изменятся.',
    goal_linked: 'Считается по остатку на счёте «{a}»',
    goal_close: 'Убрать из активных', goal_reopen: 'Вернуть в активные',
    goal_closed: 'Завершённые',
    goal_none: 'Целей пока нет',
    goal_none_hint: 'Отпуск, подушка безопасности, взнос за квартиру — приложение покажет, сколько откладывать в месяц, чтобы успеть.',
    goal_need_target: 'Укажите сумму цели',
    goal_delete_warn: 'Вместе с целью удалятся отметки о накоплениях ({n}).',
    reserved: 'Отложено на цели',
    free_money: 'Свободно',
  },
  es: {
    goal_title: 'Metas y ahorro', goal_new: 'Nueva meta',
    goal_name: 'Para qué ahorras', goal_name_ph: 'Ej.: vacaciones, fondo, coche',
    goal_target: 'Cuánto necesitas', goal_deadline: 'Para qué fecha',
    goal_deadline_hint: 'Puedes dejarlo vacío y ahorrar sin plazo.',
    goal_account: 'Dónde está el dinero', goal_account_none: 'Marcar a mano',
    goal_account_auto: 'Se toma el saldo de esa cuenta: no hay que marcar nada.',
    goal_account_manual: 'Tú marcas cuánto apartaste. No afecta los saldos.',
    goal_of: 'de', goal_left: 'faltan {v}', goal_per_month: '{v} al mes',
    goal_per_month_short: 'Al mes', goal_done: 'Meta alcanzada', goal_overdue: 'plazo vencido',
    goal_put: 'Apartar',
    goal_delete_saving: 'Lo ahorrado en la meta bajará en ese importe.', goal_added: 'Apartado', goal_history: 'Cuándo apartaste',
    goal_saving_note_ph: 'De dónde salió (opcional)',
    goal_saving_hint: 'Es una marca, no un traspaso: los saldos no cambian.',
    goal_linked: 'Se calcula con el saldo de «{a}»',
    goal_close: 'Quitar de activas', goal_reopen: 'Volver a activas', goal_closed: 'Terminadas',
    goal_none: 'Aún no hay metas',
    goal_none_hint: 'Vacaciones, fondo de emergencia, enganche: la app te dice cuánto apartar al mes.',
    goal_need_target: 'Indica el monto de la meta',
    goal_delete_warn: 'Se borrarán también las marcas de ahorro ({n}).',
    reserved: 'Apartado en metas', free_money: 'Disponible',
  },
  en: {
    goal_title: 'Goals and savings', goal_new: 'New goal',
    goal_name: 'What you are saving for', goal_name_ph: 'e.g. holiday, safety net, car',
    goal_target: 'How much you need', goal_deadline: 'By what date',
    goal_deadline_hint: 'Optional — leave empty to save without a deadline.',
    goal_account: 'Where the money sits', goal_account_none: 'Mark by hand',
    goal_account_auto: 'The balance of that account counts as saved — nothing to mark.',
    goal_account_manual: 'You mark what you set aside. Account balances are unaffected.',
    goal_of: 'of', goal_left: '{v} to go', goal_per_month: '{v} per month',
    goal_per_month_short: 'Per month', goal_done: 'Goal reached', goal_overdue: 'past due',
    goal_put: 'Set aside',
    goal_delete_saving: 'The saved amount will drop by this much.', goal_added: 'Set aside', goal_history: 'When you set aside',
    goal_saving_note_ph: 'Where it came from (optional)',
    goal_saving_hint: 'This is a note, not a transfer: balances do not change.',
    goal_linked: 'Counted from the balance of «{a}»',
    goal_close: 'Move out of active', goal_reopen: 'Move back to active', goal_closed: 'Finished',
    goal_none: 'No goals yet',
    goal_none_hint: 'Holiday, safety net, down payment — the app shows how much to set aside each month.',
    goal_need_target: 'Enter the goal amount',
    goal_delete_warn: 'The savings marks will be deleted too ({n}).',
    reserved: 'Set aside for goals', free_money: 'Free to spend',
  },
};

for (const lang of Object.keys(dict)) Object.assign(dict[lang], goals[lang]);

/* Финансовый отчёт. */
const report = {
  ru: {
    report_table: 'Отчёт по месяцам',
    unaccounted: 'Расходы без категории',
    unaccounted_hint: '{n} операций не разнесены — отчёт по категориям их не показывает',
    unaccounted_fix: 'Открыть и разнести',
    vs_prev: 'Стрелки — изменение к прошлому такому же периоду.',
  },
  es: {
    report_table: 'Reporte por mes',
    unaccounted: 'Gastos sin categoría',
    unaccounted_hint: '{n} movimientos sin clasificar: no aparecen por categoría',
    unaccounted_fix: 'Abrir y clasificar',
    vs_prev: 'Las flechas comparan con el periodo anterior.',
  },
  en: {
    report_table: 'Month by month',
    unaccounted: 'Expenses without a category',
    unaccounted_hint: '{n} transactions unclassified — they do not show by category',
    unaccounted_fix: 'Open and classify',
    vs_prev: 'Arrows compare with the previous equivalent period.',
  },
};

for (const lang of Object.keys(dict)) Object.assign(dict[lang], report[lang]);

/* Долги и стратегия погашения. */
const debts = {
  ru: {
    debt_title: 'Долги', debt_new: 'Новый долг',
    debt_name: 'Что за долг', debt_name_ph: 'Например: кредитка BBVA',
    debt_balance: 'Сколько должны сейчас',
    debt_balance_hint: 'Возьмите цифру из последней выписки — «Saldo deudor total».',
    debt_apr: 'Ставка, % годовых',
    debt_apr_hint: 'В выписке это «Tasa de interés anual aplicable». У BBVA по снятию наличных бывает 48,51%.',
    debt_iva: 'IVA на проценты (16%)',
    debt_iva_hint: 'В Мексике проценты облагаются IVA, поэтому долг обходится дороже объявленной ставки.',
    debt_min: 'Минимальный платёж', debt_due_day: 'Число платежа',
    debt_need_balance: 'Укажите сумму долга',
    debt_delete_warn: 'Вместе с долгом удалится история платежей ({n}).',
    debt_close: 'Убрать из активных', debt_reopen: 'Вернуть в активные',
    debt_total: 'Всего долгов',
    debt_confirmed: 'Сверено {d}',
    debt_stale: 'Прошло {n} дней с последней сверки — обновите остаток из выписки',
    debt_cost_title: 'Долг растёт сам',
    debt_cost_month: 'процентов в месяц',
    debt_cost_day: 'это {v} каждый день',
    debt_min_trap: 'Минимальный платёж {v} не покрывает даже проценты — при нём долг никогда не кончится',
    debt_growing: 'растёт на {v} в месяц',
    debt_interest_month: 'проценты: {v} в месяц',
    debt_how_much: 'Сколько платить в месяц',
    debt_per_month_label: 'в месяц',
    debt_free_in: 'Свобода через', debt_overpay: 'Переплата',
    debt_never: 'никогда', debt_never_long: 'При таком платеже долг не закроется никогда',
    debt_never_hint: 'Он будет расти на {v} в месяц. Платите больше, чем набегает процентов.',
    debt_months: '{n} мес.',
    debt_options: 'Варианты погашения',
    debt_col_pay: 'Платёж', debt_col_months: 'Срок', debt_col_over: 'Переплата',
    debt_options_hint: 'Нажмите на строку, чтобы посчитать этот вариант. Каждая добавленная тысяча в платеже сокращает срок сильнее, чем кажется.',
    debt_pay: 'Записать платёж', debt_paid: 'Платёж записан',
    debt_from_account: 'С какого счёта',
    debt_delete_payment: 'Остаток долга увеличится на сумму этого платежа.',
    debt_payment_note: 'Платёж по долгу: {d}',
    debt_as_expense: 'Записать и как расход',
    debt_as_expense_hint: 'Платёж по карте — это реальный уход денег со счёта. Снимите, если уже записали его вручную.',
    debt_confirm_btn: 'Сверить остаток с выпиской',
    debt_confirm_hint: 'Впишите сумму из свежей выписки. Проценты начисляет банк, поэтому раз в месяц остаток стоит сверять.',
    debt_history: 'История платежей',
    debt_none: 'Долгов нет',
    debt_none_hint: 'Кредитка, займ, рассрочка — приложение покажет, сколько они стоят в месяц и за какой срок гасятся.',
    net_worth_real: 'Чистыми',
  },
  es: {
    debt_title: 'Deudas', debt_new: 'Nueva deuda',
    debt_name: 'Qué deuda', debt_name_ph: 'Ej.: tarjeta BBVA',
    debt_balance: 'Cuánto debes ahora',
    debt_balance_hint: 'Toma el «Saldo deudor total» de tu último estado de cuenta.',
    debt_apr: 'Tasa anual, %',
    debt_apr_hint: 'En el estado de cuenta es la «Tasa de interés anual aplicable».',
    debt_iva: 'IVA sobre intereses (16%)',
    debt_iva_hint: 'En México los intereses llevan IVA, así que la deuda cuesta más que la tasa nominal.',
    debt_min: 'Pago mínimo', debt_due_day: 'Día de pago',
    debt_need_balance: 'Indica el monto de la deuda',
    debt_delete_warn: 'Se borrará también el historial de pagos ({n}).',
    debt_close: 'Quitar de activas', debt_reopen: 'Volver a activas',
    debt_total: 'Total de deudas', debt_confirmed: 'Verificado el {d}',
    debt_stale: 'Han pasado {n} días desde la última verificación',
    debt_cost_title: 'La deuda crece sola', debt_cost_month: 'de intereses al mes',
    debt_cost_day: 'son {v} cada día',
    debt_min_trap: 'El pago mínimo {v} no cubre ni los intereses: así nunca se termina',
    debt_growing: 'crece {v} al mes', debt_interest_month: 'intereses: {v} al mes',
    debt_how_much: 'Cuánto pagar al mes', debt_per_month_label: 'al mes',
    debt_free_in: 'Libre en', debt_overpay: 'Sobrepago',
    debt_never: 'nunca', debt_never_long: 'Con ese pago la deuda nunca se cierra',
    debt_never_hint: 'Crecerá {v} al mes. Paga más de lo que generan los intereses.',
    debt_months: '{n} meses',
    debt_options: 'Formas de pagarla',
    debt_col_pay: 'Pago', debt_col_months: 'Plazo', debt_col_over: 'Sobrepago',
    debt_options_hint: 'Toca una fila para calcular esa opción.',
    debt_pay: 'Registrar pago', debt_paid: 'Pago registrado',
    debt_from_account: 'Desde qué cuenta',
    debt_delete_payment: 'El saldo de la deuda aumentará en ese importe.',
    debt_payment_note: 'Pago de deuda: {d}',
    debt_as_expense: 'Registrar también como gasto',
    debt_as_expense_hint: 'El pago sí sale de tu cuenta. Desactiva si ya lo registraste.',
    debt_confirm_btn: 'Verificar saldo con el estado de cuenta',
    debt_confirm_hint: 'Escribe el saldo del estado más reciente.',
    debt_history: 'Historial de pagos',
    debt_none: 'Sin deudas',
    debt_none_hint: 'Tarjeta, préstamo, meses: la app muestra cuánto cuestan y en cuánto se liquidan.',
    net_worth_real: 'Patrimonio neto',
  },
  en: {
    debt_title: 'Debts', debt_new: 'New debt',
    debt_name: 'What debt', debt_name_ph: 'e.g. BBVA credit card',
    debt_balance: 'How much you owe now',
    debt_balance_hint: 'Take the total outstanding from your latest statement.',
    debt_apr: 'Annual rate, %',
    debt_apr_hint: 'On the statement this is the applicable annual interest rate.',
    debt_iva: 'VAT on interest (16%)',
    debt_iva_hint: 'In Mexico interest carries VAT, so debt costs more than the headline rate.',
    debt_min: 'Minimum payment', debt_due_day: 'Payment day',
    debt_need_balance: 'Enter the debt amount',
    debt_delete_warn: 'The payment history will be deleted too ({n}).',
    debt_close: 'Move out of active', debt_reopen: 'Move back to active',
    debt_total: 'Total debt', debt_confirmed: 'Checked on {d}',
    debt_stale: '{n} days since the last check — update from your statement',
    debt_cost_title: 'The debt grows by itself', debt_cost_month: 'of interest per month',
    debt_cost_day: 'that is {v} every day',
    debt_min_trap: 'The minimum payment {v} does not even cover interest — it never ends',
    debt_growing: 'growing {v} per month', debt_interest_month: 'interest: {v} per month',
    debt_how_much: 'How much to pay monthly', debt_per_month_label: 'per month',
    debt_free_in: 'Free in', debt_overpay: 'Overpaid',
    debt_never: 'never', debt_never_long: 'At this payment the debt never closes',
    debt_never_hint: 'It grows {v} per month. Pay more than the interest.',
    debt_months: '{n} months',
    debt_options: 'Ways to pay it off',
    debt_col_pay: 'Payment', debt_col_months: 'Term', debt_col_over: 'Overpaid',
    debt_options_hint: 'Tap a row to calculate that option.',
    debt_pay: 'Record a payment', debt_paid: 'Payment recorded',
    debt_from_account: 'From which account',
    debt_delete_payment: 'The debt balance will grow back by this amount.',
    debt_payment_note: 'Debt payment: {d}',
    debt_as_expense: 'Also record as an expense',
    debt_as_expense_hint: 'The payment does leave your account. Untick if already recorded.',
    debt_confirm_btn: 'Check balance against the statement',
    debt_confirm_hint: 'Enter the balance from your most recent statement.',
    debt_history: 'Payment history',
    debt_none: 'No debts',
    debt_none_hint: 'Card, loan, instalments — the app shows what they cost and how long to clear.',
    net_worth_real: 'Net worth',
  },
};

for (const lang of Object.keys(dict)) Object.assign(dict[lang], debts[lang]);

/* Счета-фактуры из архива SAT. */
const cfdiPack = {
  ru: {
    cfdi_none: 'В архиве нет счетов-фактур — похоже, это не выгрузка из SAT',
    cfdi_from_sat: 'Счета-фактуры из SAT · {rfc}',
    cfdi_skipped: 'Пропущено документов: {n} — подтверждения оплаты, переводы и повторы',
    cfdi_hint: 'Выгрузите на портале SAT «facturas emitidas» и «recibidas» архивом — приложение разберёт их точно, без распознавания.',
  },
  es: {
    cfdi_none: 'El archivo no trae CFDI: no parece una descarga del SAT',
    cfdi_from_sat: 'CFDI del SAT · {rfc}',
    cfdi_skipped: 'Documentos omitidos: {n} (complementos de pago, traslados y repetidos)',
    cfdi_hint: 'Descarga del portal del SAT tus facturas emitidas y recibidas en ZIP.',
  },
  en: {
    cfdi_none: 'No invoices in this archive — it does not look like a SAT export',
    cfdi_from_sat: 'Invoices from SAT · {rfc}',
    cfdi_skipped: 'Skipped documents: {n} (payment receipts, transfers and duplicates)',
    cfdi_hint: 'Download your issued and received invoices from the SAT portal as a ZIP.',
  },
};

for (const lang of Object.keys(dict)) Object.assign(dict[lang], cfdiPack[lang]);
